var = input('Digite algo: ')
print('É alphanumerico: ')
print(var.isalnum())
print('É letra: ')
print(var.isalpha())
print('É pontuação: ')
print(var.isascii())
print('É um digito: ')
print(var.isdigit())
